name: vy_string_utils
description: Collection of simple string Utilities.
version: 0.3.2
homepage: https://github.com/giorgiofran/vy_string_utils

environment:
  sdk: '>=2.7.1 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
