name: vy_string_utils
description: Collection of simple string Utilities.
version: 0.4.0-nullsafety
homepage: https://github.com/giorgiofran/vy_string_utils

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic:  1.10.0-nullsafety.3 #^1.9.0
  test:  1.16.0-nullsafety.13 #^1.6.0
