name: vy_string_utils
description: Simple String Utilities.
version: 0.2.1
# homepage: https://www.example.com
author: Giorgio <giorgiofran@gmail.com>

environment:
  sdk: '>=2.5.2 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: 1.8.0
  test: ^1.6.0
