name: vy_string_utils
description: Collection of simple string and other types utilities.
version: 0.4.6
homepage: https://github.com/giorgiofran/vy_string_utils

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  power_extensions: ^0.2.3  

dev_dependencies:
  lints: ^4.0.0
  test:  ^1.16.4
